allprojects {
    group = 'co.com.pragma'
    version = '0.0.53'

    ext {
        jjwtVersion = '0.12.6' // Version para JWT
    }

    repositories {
        mavenCentral()
    }

    apply plugin: 'java'
    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(21))
        }
    }

    configurations.configureEach {
        resolutionStrategy {
            force 'org.springframework:spring-beans:6.2.10'
        }
    }
}

project(':crediya-common-domain') {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    description = 'Domain module for common utilities in CrediYa microservices'

    java {
        withSourcesJar()
        withJavadocJar()
    }

    dependencies {
        // No dependencies specific to domain module itself, or add them here
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                artifactId = 'crediya-common-domain'
                pom {
                    name.set('CrediYa Common Domain')
                    description.set(project.description)
                }
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/pedro00627/crediya-common")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}

project(':crediya-common-security') {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    description = 'Security module for common utilities in CrediYa microservices'

    java {
        withSourcesJar()
        withJavadocJar()
    }

    dependencies {
        implementation project(':crediya-common-domain')
        implementation project(':crediya-common-starter') // Added this line
        implementation 'io.projectreactor:reactor-core' // Added this line

        api platform('org.springframework.boot:spring-boot-dependencies:3.2.5')
        api 'org.springframework.boot:spring-boot-starter-security'

        api "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
        runtimeOnly "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
        runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"

        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                artifactId = 'crediya-common-security'
                pom {
                    name.set('CrediYa Common Security')
                    description.set(project.description)
                }
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/pedro00627/crediya-common")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}

project(':crediya-common-starter') {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    description = 'Starter for common utilities in CrediYa microservices'

    java {
        withSourcesJar()
        withJavadocJar()
    }

    dependencies {
        implementation project(':crediya-common-domain')

        api platform('org.springframework.boot:spring-boot-dependencies:3.2.5')
        api 'org.springframework.boot:spring-boot-autoconfigure'

        api 'org.apache.logging.log4j:log4j-api'
        api 'org.apache.logging.log4j:log4j-core'
        api 'org.apache.logging.log4j:log4j-layout-template-json'

        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
                pom {
                    name.set('CrediYa Common Starter')
                    description.set(project.description)
                }
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/pedro00627/crediya-common")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}
